### ISSUE TITLE
Change .gitignore to exclude development files from git export

### ISSUE THREAD

**Issue by jorygeerts** [cmpayments/iban#2]
See https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

If we can tell `git export` to ignore things like our tests, travis and scrutinizer config, etc. a `composer install --prefer-dist` will result in a cleaner vendor directory.
As consumer of a package, I'm often not interested in the package their tests and such (and when I am, it is on my development environment, where I can just `composer install --prefer-source` to get the tests).

In essence, this would mean adding something like the following to the ~~`.gitingore`~~ `.gitattributes` file.
```
/tests              export-ignore
/.gitattributes     export-ignore
/.gitignore         export-ignore
/.travis.yml        export-ignore
/phpunit.xml        export-ignore
```

**Comment by boywijnmaalen** [comment]
Hi @jorygeerts ,

Thanks for your enhancement proposal. 

I think this would be a good addition to the package. You are most welcome to create a pull request containing the above mentioned improvement.

Two remarks tough;

- I think you're talking about .gitattributes and not .gitignore?
- We could even automate this a step further without requiring the user to append '--prefer-dist'  on the cli every time he's installing this package. This would however only work out-of-the-box when the package is not used as a dependency (if it were to be a dependency than it's up to primary composer configuration on how this package should be installed).

If we add the following to our composer.json we could even make --prefer-dist the default operation for this package (without actually specifying it on the cli).

```
"config": {
    "preferred-install": "dist"
},
"minimum-stability": "stable"
```

The minimum-stability option is necessary because ```"preferred-install": "dist"``` refers to a released version and this is usually a stable release, the two kinda go together.

Cheers!

**Comment by jorygeerts** [comment]
Ah yes, I mean `.gitattributes`.

Making the `preferred-install` of the package `dist` would make things cleaner when somebody directly clones this project, but the main goal is to make things cleaner when somebody depends on this project. When making a clone of a specific project, I would expect the whole project - if I'm checking out that specific project I'm probably interested in its test cases and such because I want to do some development.

**Comment by jorygeerts** [comment]
Well, I'm not sure which project I was locking at, but we already have this in place here.
https://github.com/cmpayments/iban/blob/master/.gitattributes

**Comment by boywijnmaalen** [comment]
Of course, it's up to you! 

But apparently this is a none-issue. I wasn't aware this was already in the package.
